package com.humanoidai.navigation

object NavRoutes {
    const val LOGIN = "login"
    const val SPLASH = "splash"
    const val DASHBOARD = "dashboard"
    const val ENROLLMENT = "enrollment"
    const val ENVIRONMENT = "environment"
    const val RECOGNITION = "recognition"
    const val ALERTS = "alerts"
    const val ASSISTANT = "assistant"
    const val HISTORY = "history"
    const val SETTINGS = "settings"
    const val APPEARANCE = "appearance"
    const val LAYOUT_CUSTOMIZATION = "layout_customization"
    const val ANALYTICS = "analytics"
    const val OWNER_ENROLLMENT = "owner_enrollment"
    const val BIOMETRIC_VERIFICATION = "biometric_verification"
    const val RUNTIME_INSPECTOR = "runtime_inspector"
    const val PRIVACY_DASHBOARD = "privacy_dashboard"
    const val SECURITY_INSPECTOR = "security_inspector"
    const val GOAL_INSPECTOR = "goal_inspector"
    const val BEHAVIOR_INSPECTOR = "behavior_inspector"
    const val EMBODIMENT_INSPECTOR = "embodiment_inspector"
    const val COORDINATION_INSPECTOR = "coordination_inspector"
}